USE MASTER;

CREATE DATABASE DBCRUDCORE;


USE DBCRUDCORE;


CREATE TABLE CONTACTO(
	IDCONTACTO INT IDENTITY PRIMARY KEY,
	NOMBRE VARCHAR(50),
	TELEFONO VARCHAR(50),
	CORREO VARCHAR(50)
);

-------------------------------------------------------------------------------
CREATE PROCEDURE SP_LISTAR
AS
BEGIN
	SELECT * FROM CONTACTO;
END
-------------------------------------------------------------------------------
CREATE PROCEDURE SP_OBTENER(
	@IDCONTACTO INT
)
AS
BEGIN
	SELECT * FROM CONTACTO WHERE IDCONTACTO = @IDCONTACTO;
END
-------------------------------------------------------------------------------
CREATE PROCEDURE SP_GUARDAR(
	@NOMBRE VARCHAR(50),
	@TELEFONO VARCHAR(50),
	@CORREO VARCHAR(50)
)
AS
BEGIN
	INSERT INTO CONTACTO(NOMBRE, TELEFONO, CORREO) VALUES (@NOMBRE, @TELEFONO, @CORREO);
END
-------------------------------------------------------------------------------
CREATE PROCEDURE SP_EDITAR(
	@IDCONTACTO INT,
	@NOMBRE VARCHAR(50),
	@TELEFONO VARCHAR(50),
	@CORREO VARCHAR(50)
)
AS
BEGIN
	UPDATE CONTACTO SET NOMBRE=@NOMBRE, TELEFONO=@TELEFONO, CORREO=@CORREO WHERE IDCONTACTO=@IDCONTACTO;
END
-------------------------------------------------------------------------------
CREATE PROCEDURE SP_ELIMINAR(
	@IDCONTACTO INT
)
AS
BEGIN
	DELETE FROM CONTACTO WHERE IDCONTACTO=@IDCONTACTO;
END


